from libvect import FloatVector

ELFE, NAIN = 0, 1
SPAWN_NAIN = FloatVector(32.0,0.0)
SPAWN_ELFE = FloatVector(0.0,0.0)

JETPACK_REFILL = 0.5
JETPACK_CONSO = 1
JETPACK_MAX = 30

COTE_CUBE = 32
SIZE_X = 3
SIZE_Y = 5

GRAVITE = FloatVector(0, 5)
JETPACK_REFILL = 0.5
JETPACK_CONSO = 1
JETPACK_MAX = 30